# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 37bb137086aa0e8d32527dc3c7e43208aed5c8ad1c263a1d2625b2db994d8b72ca26e0b74b8d13625722b94ac625aa3de016dd97ec01e474bee2a7ee453b052b
  email_provider_password: user@example.com
  email_provider_username: changeme
  address_smtp: changeme

test:
  domain_name: example.com
  secret_key_base: 7df8db090ec2f1549f8c1e832c0500c0414275bffed5db706a53e34099334dd24cbc67d53725ffd2511a70ecf96e249fcf679a8cda4ac56969f1aaf1fde2de98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_PASSWORD"] %>
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
